### ISSUE TITLE
Make "rawVBusDataOnly" configurable for connection type "Serial to LAN-Gateway"

### ISSUE THREAD

**Issue by Simpson474** [Grizzelbee/ioBroker.resol#103]
There are two different types of "Serial to LAN-Gateways":
- Standard, for example ser2net on Linux or IoT devices running for example [Tasmota](https://tasmota.github.io/docs/Serial-to-TCP-Bridge/)
- Proprietary, for example Resol VBus/LAN interface adapter or [serial-to-tcp example](https://github.com/danielwippermann/resol-vbus/tree/master/examples/serial-to-tcp) from @[danielwippermann](https://github.com/danielwippermann/resol-vbus/commits?author=danielwippermann)

The main difference seems to be the handshake which is required for the proprietary gateways. This handshake can be disabled in resol-vbus library by setting "rawVBusDataOnly" to "true" in "vbus.TcpConnection". However, the corresponding option seems to be hardcoded in ioBroker.resol and cannot be changed in the settings. I am using ser2net on a Raspberry Pi and ioBroker.resol works fine after changing the setting to "true" directly in "main.js". Please note that no password is required in this case, i.e. not setting a password should not cause an error being reported by ioBroker.resol.

**Comment by Grizzelbee** [comment]
Sounds to mw like it should get implemented. I'll take a look into it soon.

**Comment by Simpson474** [comment]
It looks already implemented, but I cannot find any possibility in the settings of the adapter to change "this.config.vbusDataOnly" to true except by directly editing the source code. Maybe I have overlooked something, but even the full text search for "vbusDataOnly" only reveals two locations - the one you have cited above and the initialization of the variable in "io-package.json" to "false".

**Comment by Grizzelbee** [comment]
Ah. Okay. Now I understand. All we need is a meaninful config option to edit this rawVBusDataOnly since the link was forgotton or got lost.
What do you thing would be a good name for this checkbox and what about a short description/tooltipp? Sorry for asking, but you are much deeper into this than me, since I own a KM2. I have no experience with those serial gateways.

**Comment by Simpson474** [comment]
Yes, the missing config option is the main issue. The second (smaller) issue is the password field which has to be filled as the adapter won't startup without a password (log message "Password is missing!"). The password won't be used if "rawVBusDataOnly" is set, i.e. any password can be entered. However, not checking for a not required password would be better.

Regarding the name and the description of the option: after checking the code again, I am not sure, whether the "Serial to LAN-Gateway" option wasn't meant initially exactly for that purpose. The differences between "VBus / LAN" (i.e. "lan") and "Serial to LAN-Gateway" (i.e. "langw") seem to be just the "password" and the "rawVBusDataOnly" member:
```javascript
case 'lan':
    ctx.connection = new vbus.TcpConnection({
        host: this.config.connectionIdentifier,
        port: this.config.connectionPort,
        password: this.config.vbusPassword
    });
    this.log.info('TCP Connection via LAN to [' + this.config.connectionIdentifier + ':' + this.config.connectionPort + '] selected');
    break;
```

```javascript
case 'langw':
    ctx.connection = new vbus.TcpConnection({
        host: this.config.connectionIdentifier,
        port: this.config.connectionPort,
        rawVBusDataOnly: this.config.vbusDataOnly
    });
    this.log.info('TCP Connection via LAN-gw to [' + this.config.connectionIdentifier + ':' + this.config.connectionPort + '] selected');
    break;
```

I don't see any use case for "langw" if "rawVBusDataOnly" is set to "false" as this option is already covered by "lan". Adding the "new" option might be as easy as doing the following change:
```javascript
case 'langw':
    ctx.connection = new vbus.TcpConnection({
        host: this.config.connectionIdentifier,
        port: this.config.connectionPort,
        rawVBusDataOnly: true
    });
    this.log.info('TCP Connection via LAN-gw to [' + this.config.connectionIdentifier + ':' + this.config.connectionPort + '] selected');
    break;
```

```javascript
function testPassword(config) {
    if (config.connectionDevice === 'lan' && (!config.vbusPassword || '' === config.vbusPassword)) {
        reject('Password is missing!');
    }
}
```

**Comment by Grizzelbee** [comment]
> Yes, the missing config option is the main issue. The second (smaller) issue is the password field which has to be filled as the adapter won't startup without a password (log message "Password is missing!"). The password won't be used if "rawVBusDataOnly" is set, i.e. any password can be entered. However, not checking for a not required password would be better.

I totally understand that point and I'm planning to implement it that way - but to boil the LAN / LANGW discussion down:
You wrote in your first post:
>There are two different types of "Serial to LAN-Gateways":
>*  Standard, for example ser2net on Linux or IoT devices running for example [Tasmota](https://tasmota.github.io/docs/Serial-to-TCP-Bridge/)
>* Proprietary, for example Resol VBus/LAN interface adapter or [serial-to-tcp example](https://github.com/danielwippermann/resol-vbus/tree/master/examples/serial-to-tcp) from @[danielwippermann](https://github.com/danielwippermann/resol-vbus/commits?author=danielwippermann)

from that statement I got that we need to differentiate two types of lan-gateways:
1. Types that need the `rawVBusDataOnly` option set to `true` and
2. Types that need the `rawVBusDataOnly` option set to `false`

If that is true we need an configuable option in the admin interface and a change of the password check.

If that is false and your first statements differentiated between LAN-Gateways like KM2 and Serial-to-LAN-Gateways - wich are already differentiated in the Config - you are right and we don't need a new config checkbox for `rawVBusDataOnly` but only the `true` hardcoded and the password check disabled in case that option is checked.

So this is the point we need to clarify and if we need a new checkbox - a good name and description for it that anybody who uses such a gateway will understand what to do.

**Comment by Simpson474** [comment]
> If that is false and your first statements differentiated between LAN-Gateways like KM2 and Serial-to-LAN-Gateways - wich are already differentiated in the Config - you are right and we don't need a new config checkbox for rawVBusDataOnly but only the true hardcoded and the password check disabled in case that option is checked.

This should be correct. A gateway requiring a handshake with authentication can be used with the VBus/LAN option (or KM2/DL2 option). A gateway not requiring a handshake, but directly converting serial to LAN can be used with the Serial-to-LAN Gateway option.

**Comment by Grizzelbee** [comment]
Done as requested. rawvBusDataOnly=true is hardcoded and config test ignores missing password.

**Comment by Simpson474** [comment]
I have updated the adapter today and it seems to work fine.
