### ISSUE TITLE
	State value to set for "resol.0.0022110010.8721.000010221110010002220" has to be type "number" but received type "string" 

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.resol#27]
Would be much easier to detect whether it's a number by testing whether `item.type` is 'number' since this info is used to create the data point.

```
                        this.createOrExtendObject(resolId + actionPath + item.dpName, {
                            type: 'state',
                            common: {
                                name: item.dpName,
                                type: item.type,
                                min: item.min,
                                max: item.max,
                                states: item.states,
                                role: thisRole,
                                read: true,
                                write: true
                            },
```

![grafik](https://user-images.githubusercontent.com/5459426/117828396-0da70e80-b272-11eb-8310-c686fd8b5de1.png)

**Comment by SurfGargano** [comment]
Definiert wird der Type im Setup File, also warum der Check ? Ich denke die Warnung kam wo anders her.

**Comment by Grizzelbee** [comment]
Naja, der Fehler wird ja immer dann geworfen,  wenn ein Datenpunkt mit Typ "number" definiert wurde und beim setState() ein String übergeben wird. JS konvertiert das durch die lose Typisierung zwar in aller Regel richtig, aber sauber ist das nicht. Deshalb meine Aussage: Am besten auf item.type==='number' des Zieldatenpunktes testen (und nicht ob der value zufällig wie eine Zahl aussieht) und dann den value für setState() mit einem Number.parseFloat(value)/.parseInt(value) korrekt konvertieren. Das ist dann sauber weil der geschriebene Value zur Erwartung des Datenpunktes passt. Sollte bei der Konvertierung des Values etwas schief gehen (exception) muss ggf. vorher noch weiter geprüft oder die Erartungshaltung überdacht weden.

**Comment by SurfGargano** [comment]
fixed in 0.3.1
