### ISSUE TITLE
with iobroker.resol (daniel wippermann) v 0.22.0 the connection can't be established

### ISSUE THREAD

**Issue by SurfGargano** [Grizzelbee/ioBroker.resol#33]
Daniel has changed the connection procedure in thje v0.22.0 , so an error is shown and no connection is established : Unable to create optimizer for master with address 0x1121

**Comment by Grizzelbee** [comment]
>Changelog iobroker.resol (daniel wippermann)
>### Version 0.22.0 (2021-05-10)
>*  [BREAKING CHANGE] Dropping support for Node.js versions < 12

What first comes to my mind: what nodeJs version do you use?

**Comment by SurfGargano** [comment]
NodeJS 12.22.1

**Comment by SurfGargano** [comment]
Wird eigentlich resol-vbus mit installiert , wenn ich iobroker.resol installiere ?
Das war nämlich mein Problem, weil es 2 Installationen gab und in der Installation mit iobroker.resol fehlten die Optimizer files

**Comment by SurfGargano** [comment]
Wird eigentlich resol-vbus mit installiert , wenn ich iobroker.resol installiere ?
Das war nämlich mein Problem, weil es 2 Installationen gab und in der Installation mit iobroker.resol fehlten die Optimizer files

**Comment by SurfGargano** [comment]
Hab gesehen: Resol-vbus wird mit installiert
