### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by graebec** [Grizzelbee/ioBroker.resol#62]
Good Morning I am relatively new to I-broker and this is the first time I tried to install an adapter via URL. 

I received an error installing : 
iobroker host.raspberrypi Cannot install Grizzelbee/ioBroker.resol#e6e4f3dfcd1b7ad57c17a2bd14d37fed6ff14838: 1
The log looks like this : 

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   'Grizzelbee/ioBroker.resol#e6e4f3dfcd1b7ad57c17a2bd14d37fed6ff14838',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/iobroker'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v12.22.7
4 verbose npm-session 58f0a351f021edb0
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 verbose prepareGitDep github:Grizzelbee/ioBroker.resol#e6e4f3dfcd1b7ad57c17a2bd14d37fed6ff14838: installing devDeps and running prep$
8 silly fetchPackageMetaData error for github:Grizzelbee/ioBroker.resol#e6e4f3dfcd1b7ad57c17a2bd14d37fed6ff14838 premature close
9 timing stage:rollbackFailedOptional Completed in 4ms
10 timing stage:runTopLevelLifecycles Completed in 6394ms
11 verbose stack Error: premature close
11 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
11 verbose stack     at PassThrough.emit (events.js:326:22)
11 verbose stack     at emitCloseNT (internal/streams/destroy.js:69:8)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
12 verbose cwd /opt/iobroker
13 verbose Linux 5.10.63-v7+
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "Grizzelbee/ioBroker.resol#e6e4f3dfcd1b7ad57c17a2bd14d37fed6ff14838" "--prefi$
15 verbose node v12.22.7
16 verbose npm  v6.14.15
17 error premature close
18 verbose exit [ 1, true ]

Did I make a mistake ? 

Thank you very much in Advance

**Comment by Grizzelbee** [comment]
@graebec 
There isn't very much you can do wrong during manual installation, but sometimes it fails without offering the deaper reason. On my systems as well. Anyway....
please try:
* login to a terminal on your RasPi and enter the following two commands (sudo is only needed if your not logged in as root)
* cd /opt/iobroker
* sudo npm install iobroker.resol@0.3.2

this should do the manual installation via npm which should me more statble than ioBroker URL-Installation.

And please take my apologies for the inconveniance. I'm still on the way getting the adapter into the repos.

**Comment by graebec** [comment]
@Grizzelbee 
Thank you very much - that helped! Working really good. 
Just as a feedback: (maybe you already know) after installing the adapter I had to run the install from the adapter context  in I-broker to create an instance for it. 

Cheers ! Best Regards
