### ISSUE TITLE
How to customize min and max values for temperature channels?

### ISSUE THREAD

**Issue by UweSauter** [Grizzelbee/ioBroker.resol#94]
I'm using ioBroker.resol with the VBus/LAN interface to monitor a [Cosmo Multi2](https://www.cosmo-info.de/produkte/heizungstechnik/solartechnik/regelungen/regelung-multi-2) which seems to be a rebranded [Resol DeltaSol E](https://www.resol.de/de/produktdetail/8) with customized firmware.
The issue I have is that the Cosmo Multi2 reports 888.88°C as placeholder for all temperature channels that have no sensor connected. This results in a warning every 30s for every channel that is not connected.
Is there a way
- to either increase the max temperature of those channels to silence the warning?
- or to teach the adapter that 888.88°C is Cosmo's way of telling that the channel has no sensor connected?

Thanks for you work!

**Comment by Grizzelbee** [comment]
I picked that (teach the adapter that 888.88°C is Cosmo's way of telling that the channel has no sensor connected?) solution and implemented it in V1.0.0.
Hope it works for you. If not, please reopen this issue.

**Comment by UweSauter** [comment]
Thank you, that fixed the recurring warnings.
